/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eecs.ai.p1;

import eecs.ai.p1.commands.PrintState;
import eecs.ai.p1.commands.SetState;
import eecs.ai.p1.commands.*;

public class App {
    public static void main(String[] args) {

        //Create the board
        Board gameBoard = new Board();
        PrintState.of().execute(gameBoard);

        // SetState.of("876543210").execute(gameBoard);
        // PrintState.of().execute(gameBoard);
        Move.of("UP").execute(gameBoard);
        // PrintState.of().execute(gameBoard);
        Move.of("Left").execute(gameBoard);
        // PrintState.of().execute(gameBoard);
        Move.of("Right").execute(gameBoard);
        // PrintState.of().execute(gameBoard);
        Move.of("Right").execute(gameBoard);
        // PrintState.of().execute(gameBoard);

        RandomizeState.of(0).execute(gameBoard);
        // PrintState.of().execute(gameBoard);
        RandomizeState.of(2).execute(gameBoard);
        // PrintState.of().execute(gameBoard);
        // RandomizeState.of(10).execute(gameBoard);
        // PrintState.of().execute(gameBoard);
        RandomizeState.of(100).execute(gameBoard);
        // PrintState.of().execute(gameBoard);




        //Create the list of commands

        //Run through the list of commands
    }
}
