/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eecs.ai.p1;

import eecs.ai.p1.commands.PrintState;
import eecs.ai.p1.commands.SetState;

public class App {
    public static void main(String[] args) {

        //Create the board
        Board gameBoard = new Board();
        PrintState.of().execute(gameBoard);

        SetState.of("876543210").execute(gameBoard);

        PrintState.of().execute(gameBoard);

        //Create the list of commands

        //Run through the list of commands
    }
}
